return {
  "sphamba/smear-cursor.nvim",
  opts = {
	cursor_color = "#414886",
	particles_enabled = true,
	stiffnes = 0.9,
	trailing_stiffness = 0.2,
	trailing_exponent = 5,
	damping = 0.6,
	gradient_exponent = 0,
	gamma = 1,
	never_draw_over_target = true,
	hide_target_hack = true,
	particle_spread = 2,
	particles_per_second = 500,
	particles_per_length = 50,
	particle_max_lifetime = 800,
	particle_max_num = 300,
	particle_max_initial_velocity = 20,
	particle_velocity_from_cursor = 0.5,
	particle_damping = 0.15,
	particle_gravity = -100,
	min_distance_emit_particles = 0,
  },
}
